### ISSUE TITLE
[Feature Request] Floating Point Error Estimation Framework to do checklist

### ISSUE THREAD

**Issue by grimmmyshini** [vgvassilev/clad#295]
This issue is to keep track of features to implement in the floating-point error estimation framework.

**Good things to do:**

 - [x] Add a demo to demonstrate how clad can be used to detect numerical instability of algorithms.
*The above is blocked due to the fact that we have no way to automatically print error stats yet.*
 - [x] Add more tests for loops and arrays
*Blocked because of #245 and #246 .*
 - [x] Fix links in the custom model README.md 
*The above is blocked because we do not have tutorials hosted anywhere as of yet.*
- [x] ~~Optimize stores
*There are places where we can optimize our store, however, it introduces a certain amount of complexity into the code which might not be a good tradeoff. This is blocked because some discussion should be done relating to this.*~~
 - [x] Update clad README.md
*Blocked because some discussion is needed here.*

**Future work:**

 - Addition of code to implement forward propagation of errors would be an interesting project. This will help us generalize the error estimation framework.
 - Lossy compression and precision tuning. This can be implemented fairly easily, however, we would need to make another pass of the function to actually compress variables.

**Comment by grimmmyshini** [comment]
The future work section might be useful for propagating error information from numerical differentiation. Conversations relating to the same can be found [here](https://github.com/vgvassilev/clad/pull/261#discussion_r692419787).

**Comment by vgvassilev** [comment]
@grimmmyshini have we resolved that blocker? I believe so, maybe we can add this missing item and move on?

**Comment by vgvassilev** [comment]
This was implemented in clad -- we have a paper on it even.
